name: Run imap-d tests
on: [push, pull_request]

jobs:
  test:
    name: imap-d D tests
    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-20.04, windows-latest]
        dc: [dmd-latest, ldc-latest]

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2

      - name: Install openssl on Windows
        if: matrix.os == 'windows-latest'
        run: | 
          choco install --no-progress openssl
          Copy-Item "C:\Program Files\OpenSSL-Win64\lib\libssl.lib" -Destination $PSScriptRoot
          echo "LIB=C:\Progra~1\OpenSSL-Win64\lib" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
          Get-ChildItem -Recurse "C:\Program Files\OpenSSL-Win64\lib"
          
      - name: Install D compiler
        uses: dlang-community/setup-dlang@v1
        with:
          compiler: ${{ matrix.dc }}

      - name: dub build
        run: dub build

      - name: debug ls sdsd
        if: matrix.os == 'windows-latest'
        run: Get-ChildItem $Env:LIB

      - name: Build example with dub
        run: dub build --root=example

      - name: Build test with dub
        run: dub build --root=test

      - name: Run all unittests with coverage
        run: dub test --build=unittest-cov

      - name: Upload coverage to codecov
        uses: codecov/codecov-action@v2
        with:
          verbose: true
